name: Lint with ruff and Format with black

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Determine changed files based on event type
      - name: Get changed files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > changed_files.txt
          else
            git diff --name-only HEAD^ HEAD > changed_files.txt
          fi
      
      # Set up Python and cache
      - name: Set up Python and cache
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff==0.4.8
      
      # Run black and ruff only on changed files
      - name: Format with black and ruff
        run: |
          while IFS= read -r file; do
            black "$file"
            ruff --output-format=github --fix "$file"
          done < changed_files.txt
      
      # Check for changes and commit if needed
      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "style: format code with black and ruff"
            git push
          else
            echo "No changes to commit"
