name: Format

on:
  push:
    branches:
      - main
      - dev
      - testing-CI

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Fetch list of changed .py files
      - name: Get changed .py files
        id: changed-files
        run: |
          git diff --name-only ${{ github.event.before }}...${{ github.sha }} | grep '\.py$' > changed_py_files.txt || true
          
      # Set up Python and cache dependencies
      - name: Set up Python and cache
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff==0.4.8
      
      # Format changed .py files with black and ruff
      - name: Format with black and ruff
        run: |
          cat changed_py_files.txt | xargs black
          cat changed_py_files.txt | xargs -I % ruff --output-format=github --fix %
      
      # Check for changes and commit if needed
      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "style: format code with black and ruff"
            git push
          else
            echo "No changes to commit"
